# Generated by Django 4.1 on 2022-08-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flight_dest_alter_flight_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=32)),
                ('last', models.CharField(max_length=32)),
                ('flights', models.ManyToManyField(related_name='passengers', to='flights.flight')),
            ],
        ),
    ]
